version: 2
jobs:
  test_regression_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.9.0
    steps:
      - checkout
      - run:
          name: Install Packages
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/regression_model/requirements.txt --upgrade
      - run:
          name: Print Debug Information
          command: |
            . venv/bin/activate
            python --version
            pip list
      - run: 
          name: Runing Test
          command: |
            chmod +x ./scripts/fetch_kaggle_dataset.sh
            ./scripts/fetch_kaggle_dataset.sh
            py.test -vv packages/regression_model/tests
      


workflows:
  version: 2
  test-all:
    jobs:
      - test_regression_model
